import {subjects} from "./subjects.js";
import {abbreviations} from "./abbreviations.js";

export let mappings = new Map();
mappings.set(subjects.D, abbreviations.D);
mappings.set(subjects.E, abbreviations.FS);
mappings.set(subjects.F, abbreviations.FS);
mappings.set(subjects.L, abbreviations.FS);
mappings.set(subjects.SN, abbreviations.FS);
mappings.set(subjects.BK, abbreviations.KF);
mappings.set(subjects.MU, abbreviations.KF);
mappings.set(subjects.G, abbreviations.GW);
mappings.set(subjects.EK, abbreviations.GW);
mappings.set(subjects.SK, abbreviations.GW);
mappings.set(subjects.M, abbreviations.M);
mappings.set(subjects.PH, abbreviations.NW);
mappings.set(subjects.CH, abbreviations.NW);
mappings.set(subjects.BI, abbreviations.NW);
mappings.set(subjects.IN, abbreviations.INF);
mappings.set(subjects.ER, abbreviations.R);
mappings.set(subjects.KR, abbreviations.R);
mappings.set(subjects.ET, abbreviations.R);
mappings.set(subjects.SP, abbreviations.SP);
mappings.set(subjects.PI, abbreviations.PHI);