export var subjects;
(function (subjects) {
    subjects[subjects["D"] = 0] = "D";
    subjects[subjects["E"] = 1] = "E";
    subjects[subjects["F"] = 2] = "F";
    subjects[subjects["L"] = 3] = "L";
    subjects[subjects["SN"] = 4] = "SN";
    subjects[subjects["BK"] = 5] = "BK";
    subjects[subjects["MU"] = 6] = "MU";
    subjects[subjects["DS"] = 7] = "DS";
    subjects[subjects["G"] = 8] = "G";
    subjects[subjects["EK"] = 9] = "EK";
    subjects[subjects["SK"] = 10] = "SK";
    subjects[subjects["EKSK"] = 11] = "EKSK";
    subjects[subjects["M"] = 12] = "M";
    subjects[subjects["PH"] = 13] = "PH";
    subjects[subjects["CH"] = 14] = "CH";
    subjects[subjects["BI"] = 15] = "BI";
    subjects[subjects["IN"] = 16] = "IN";
    subjects[subjects["ER"] = 17] = "ER";
    subjects[subjects["KR"] = 18] = "KR";
    subjects[subjects["ET"] = 19] = "ET";
    subjects[subjects["SP"] = 20] = "SP";
    subjects[subjects["PI"] = 21] = "PI";
})(subjects || (subjects = {}));
